
server:
  port: 8100

spring:
  application:
    name: ms-enrollment
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/sis-323-test}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:admin}
    jpa:
      hibernate:
        ddl-auto: none

keycloak:
  auth-server-url: http://localhost:8080
  autodetect-bearer-only: true
  credentials:
    secret: CalOb9h83bEQEGYqaduEg0p4CFzaNnEa
    realm: sis-323
    resource: pm-backend

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka/}


